spring.application.name=AbonnementService
server.port=8009

# H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2

# Datasource
spring.datasource.username=4twin
spring.datasource.password=4twin
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:h2:file:~/test_projectAb
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.h2.console.settings.web-allow-others=true

# Eureka Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true

